routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'proyek@index');

Auth::routes();

Route::post('/register/custom',[
	'uses'=>'signUpController@create',
	'as'=>'register.custom',
]);

Route::post('/login/custom',[
	'uses'=>'loginController@login',
	'as'=>'login.custom',
]);

Route::group(['middleware'=>'auth'],function(){
	Route::get('dashboard',function(){
		return view('dashboard');
	})->name('dashboard');
	Route::get('customer',function(){
		return view('index');
	})->name('customer');
});

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/BuatToko','BuatTokoController');

Route::resource('/DaftarBarang','DaftarBarangController');

Route::resource('/TambahBarang','TambahBarangController');

app/TambahBarang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TambahBarang extends Model
{
    protected $fillable=[
    	'nama_produk','deskripsi_produk','gambar','stok','harga','id_toko',
    ];
}

app/Http/Controllers/TambahBarangController.php
<?php

namespace App\Http\Controllers;

use App\TambahBarang;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\produk;

class TambahBarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('TambahBarang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $produks = New produk;
        $produks->id_toko = Auth::id();
        $produks->nama_produk = $request->nama_produk;
        // $tokos->gambar-toko = $request->gambar-toko;
        $produks->harga = $request->harga;
        $produks->stok= $request->stok;
        $produks->deskripsi = $request->deskripsi;
        if ($request->gambar) {
            $date=date('dmYHis').'.jpg';
            $request->gambar->storeAs('public/image/barang/','Barang-'.$date);
            $produks->gambar='Barang-'.$date;
        }

        $produks->save();

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TambahBarang  $tambahBarang
     * @return \Illuminate\Http\Response
     */
    public function show(TambahBarang $tambahBarang)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TambahBarang  $tambahBarang
     * @return \Illuminate\Http\Response
     */
    public function edit(TambahBarang $tambahBarang)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TambahBarang  $tambahBarang
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TambahBarang $tambahBarang)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TambahBarang  $tambahBarang
     * @return \Illuminate\Http\Response
     */
    public function destroy(TambahBarang $tambahBarang)
    {
        //
    }
}

resources/views/TambahBarang/create.blade.php
@extends('layouts.mine')

@section('content')
	<div class="row justify-content-center">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">Tambah Produk</div>

					<div class="card-body">
							<form action="{{route('TambahBarang.store')}}" method="post" enctype="multipart/form-data">
								{{csrf_field()}}
								 <div class="form-group">
								 	 <div class="form-group col-md-8">
								    <label for="formGroupExampleInput">Nama Produk</label>
								    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Nama Produk" name="nama_produk">
								  </div>
								</div>
								
								  <div class="form-group">
								  	 <div class="form-group col-md-8">
								    <label for="exampleFormControlFile1">Gambar Produk</label>
								    <input type="file" class="form-control-file" id="exampleFormControlFile1" name="gambar">
								  </div>
								
								 <div class="form-group">
								 	 <div class="form-group col-md-8">
								    <label for="formGroupExampleInput">Harga Produk</label>
								    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Harga Produk" name="harga">
								  </div>

								<!--  <div class="form-group">
								 	 <div class="form-group col-md-8">
								    <label for="formGroupExampleInput">Potongan Harga</label>
								    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Potongan Harga" >
								  </div> -->
								 <!--  <div class="form-group col-md-8">	
									  <div class="input-group input-group-sm mb-6 col-md-4">
									  	<label for="formGroupExampleInput">Info Tambahan</label>
										  <div class="input-group-prepend">
										    <span class="input-group-text" id="inputGroup-sizing-sm">Small</span>
										  </div>
										  <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
									</div>
									</div>
								</div> -->

								 <div class="form-group">
								 	 <div class="form-group col-md-8">
								    <label for="formGroupExampleInput">Stok</label>
								    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Stok" name="stok">
								  </div>

								<div class="form-group">
									 <div class="form-group col-md-8">
								    <label for="exampleFormControlTextarea1">Deskripsi Produk</label>
								    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Deskripsi Produk" name="deskripsi_produk"></textarea>
								  </div>
								  <div class="form-group">
								  	<center><button type="submit" class="btn btn-primary" style="margin-left: 70%">{{ __('Submit') }} </button></center>
								  </div>
							  </form>
						</div>
				</div>
			</div>
		</div>
	</div>
@endsection